In [21]:
import os
from PIL import Image
import numpy as np

# Define the path to your dataset
dataset_path = "D:\myprojects\signlanguageml\images\dataset"

# Initialize lists to store images and labels
images = []
labels = []

# Loop through each folder (alphabet)
for label, alphabet in enumerate(os.listdir(dataset_path)):
    alphabet_path = os.path.join(dataset_path, alphabet)
    for image_name in os.listdir(alphabet_path):
        image_path = os.path.join(alphabet_path, image_name)
        if os.path.isfile(image_path):  # Check if the path is a file
            try:
                image = Image.open(image_path)  # Load image
                images.append(np.array(image))  # Convert image to numpy array
                labels.append(label)  # Assign a numeric label to each alphabet
            except Exception as e:
                print(f"Error loading image {image_path}: {e}")

# Convert lists to numpy arrays
images = np.array(images)
labels = np.array(labels)

#printing image and labels
print(images)
print(labels)
print("label ")
print(images.shape)

#resize  and normalize images
# Resize images
resized_images = [image.resize(64,64) for image in images]
resized_images = np.array(resized_images)

# Normalize pixel values
normalized_images = resized_images/ 255.0

[[[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [ 95 113  89]
   ...
   [ 17  15  18]
   [ 16  14  17]
   [255 255 255]]

  ...

  [[255 255 255]
   [255 255 255]
   [118 126 113]
   ...
   [ 19  15  14]
   [ 17  13  12]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [119 127 113]
   ...
   [ 17  13  12]
   [ 16  12  11]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]]


 [[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [ 26  22  19]
   ...
   [ 37  34  25]
   [ 36  33  24]
   [255 255

ValueError: cannot resize this array: it does not own its data