In [ ]:
import os
import pandas as pd

# Define the path to your dataset
dataset_path = 'D:\myprojects\signlanguageml\images\dataset'

# Initialize lists to store image paths and labels
image_paths = []
labels = []

# Loop through each folder (A, B, C, ..., Z)
for folder_name in os.listdir(dataset_path):
    folder_path = os.path.join(dataset_path, folder_name)
    
    # Ensure it's a directory
    if os.path.isdir(folder_path):
        # Loop through each image in the folder
        for image_name in os.listdir(folder_path):
            image_path = os.path.join(folder_path, image_name)
            
            # Append the image path and label (folder name) to the lists
            image_paths.append(image_path)
            labels.append(folder_name)

# Create a DataFrame to store the image paths and labels
data = pd.DataFrame({
    'image_path': image_paths,
    'label': labels
})

# Save the DataFrame to a CSV file for future use
data.to_csv('labeled_dataset.csv', index=False)

print("Labeling completed and saved to 'labeled_dataset.csv'.")

[[[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [ 95 113  89]
   ...
   [ 17  15  18]
   [ 16  14  17]
   [255 255 255]]

  ...

  [[255 255 255]
   [255 255 255]
   [118 126 113]
   ...
   [ 19  15  14]
   [ 17  13  12]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [119 127 113]
   ...
   [ 17  13  12]
   [ 16  12  11]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]]


 [[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]

  [[255 255 255]
   [255 255 255]
   [ 26  22  19]
   ...
   [ 37  34  25]
   [ 36  33  24]
   [255 255

ValueError: cannot resize this array: it does not own its data

In [ ]:
from function import *
from time import sleep
import cv2
import os
import numpy as np
import mediapipe as mp

# Define actions for Q and R
actions = ['Q', 'R']  # Only process these two actions
no_sequences = 37
sequence_length = 37
DATA_PATH = 'D:/myprojects/signlanguageml/data'

# Create directories for data storage
for action in actions: 
    for sequence in range(no_sequences):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

# Set up mediapipe hands model
mp_hands = mp.solutions.hands
with mp_hands.Hands(
    model_complexity=0,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5) as hands:
    
    # Loop through actions (now just Q and R)
    for action in actions:
        # Loop through sequences aka videos
        for sequence in range(no_sequences):
            # Loop through video length aka sequence length
            for frame_num in range(sequence_length):

                # Read frame from dataset folder
                frame = cv2.imread(f'images/dataset/{action}/{sequence}.png')

                # Check if the frame is read correctly
                if frame is None:
                    print(f"Error: Unable to read image 'images/{action}/{sequence}.png'")
                    continue

                # Make detections using MediaPipe
                image, results = mediapipe_detection(frame, hands)
                
                # Draw landmarks on the frame (Optional)
                draw_styled_landmarks(image, results)
                
                # Display the frame with landmarks
                if frame_num == 0:
                    cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(image, f'Collecting frames for {action} Video Number {sequence}', (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    cv2.imshow('OpenCV Feed', image)
                    cv2.waitKey(200)
                else: 
                    cv2.putText(image, f'Collecting frames for {action} Video Number {sequence}', (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    cv2.imshow('OpenCV Feed', image)
                
                # Export keypoints
                keypoints = extract_keypoints(results)

                # Ensure keypoints have the correct size and save them
                npy_path = os.path.join(DATA_PATH, action, str(sequence), f"{frame_num}.npy")
                np.save(npy_path, keypoints)

                # Gracefully break loop if 'q' is pressed
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
    
    # Close the OpenCV window
    cv2.destroyAllWindows()


Error: Unable to read image 'images/dataset/Q/0/0.png'
Error: Unable to read image 'images/dataset/Q/0/1.png'
Error: Unable to read image 'images/dataset/Q/0/2.png'
Error: Unable to read image 'images/dataset/Q/0/3.png'
Error: Unable to read image 'images/dataset/Q/0/4.png'
Error: Unable to read image 'images/dataset/Q/0/5.png'
Error: Unable to read image 'images/dataset/Q/0/6.png'
Error: Unable to read image 'images/dataset/Q/0/7.png'
Error: Unable to read image 'images/dataset/Q/0/8.png'
Error: Unable to read image 'images/dataset/Q/0/9.png'
Error: Unable to read image 'images/dataset/Q/0/10.png'
Error: Unable to read image 'images/dataset/Q/0/11.png'
Error: Unable to read image 'images/dataset/Q/0/12.png'
Error: Unable to read image 'images/dataset/Q/0/13.png'
Error: Unable to read image 'images/dataset/Q/0/14.png'
Error: Unable to read image 'images/dataset/Q/0/15.png'
Error: Unable to read image 'images/dataset/Q/0/16.png'
Error: Unable to read image 'images/dataset/Q/0/17.png'
Er